name: Build and Deploy to trinity

on:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Build
        uses: actions/jekyll-build-pages@v1

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Add remote host to known_hosts
        run: |
          mkdir -p ~/.ssh
          echo "trinity.hacklab.fi ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEbuUzPWSkuCC/iAE2KgxnCO22+9MLdTfTGLiVFOC6gm" >> ~/.ssh/known_hosts

      - name: Deploy to server via rsync
        run: |
          rsync -rltz --delete --omit-dir-times _site/ hackfi@trinity.hacklab.fi:/var/www/hacklab.fi/

