name: Build and Deploy to trinity

on:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Install dependencies
        run: bundle install

      - name: Build site
        run: bundle exec jekyll build

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Enable SSHFP checking
        run: |
          mkdir -p ~/.ssh
          echo "Host trinity.hacklab.fi
          VerifyHostKeyDNS yes
          StrictHostKeyChecking yes" >> ~/.ssh/config

      - name: Deploy to server via rsync
        run: |
          rsync -avz --delete _site/ hackfi@trinity.hacklab.fi:/var/www/hacklab.fi/

